### ISSUE TITLE
Group assignment is not persistent

### ISSUE THREAD

**Issue by msiebke** [zammad/zammad-helm#148]
### **BUG REPORT**

**Version of Helm and Kubernetes**:
Helm version: 3.9.4
K8s version: v1.22.8+rke2r1
Zammad version: helm.sh/chart=zammad-6.7.1, zammad/zammad-docker-compose:zammad-5.2.1-6

**What happened**:
The user's group assignment is canceled after an undefined period of time.

**What you expected to happen**:
The group assignment should not change easily.

**How to reproduce it** (as minimally and precisely as possible):
I assign the user to one or more groups and wait until it happens again.

**Anything else we need to know**:

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
