### ISSUE TITLE
static names for container-name 

### ISSUE THREAD

**Issue by klml** [zammad/zammad-helm#265]
Currently we are using dynamic container-name (eg [name: {{ .Chart.Name }}-nginx](https://github.com/zammad/zammad-helm/blob/main/zammad/templates/deployment-nginx.yaml#L28) This is sometimes confusing.

**Version of Helm and Kubernetes**:

zammad-12.0.0 

**What you expected to happen**:

static container names

**Anything else we need to know**:

@monotek

**Comment by mgruner** [comment]
Isn't the dynamic naming by design @klml? With every Helm install, the application is given a name. This should be reflected in the objects to make it possible that instances of the same application can coexist, which would not work with static names. Or did I miss something here?

I agree about the inconsistency and the bug in ingress, we should definitely improve that.

**Comment by monotek** [comment]
Yes, the k8s resources itself should take over at least parts of the name of the chart, so the same chart can be installed multiple times in the same namespace.

The names inside the resources, like containernames, could be static.
Sometimes `helm create` usese the "{{ .Chart.Name }}" var by default, which should not change but if there are some names which use the "fullname" var and some are static we should allign that.

**Comment by klml** [comment]
@mgruner you are right

> I agree about the inconsistency and the bug in ingress, we should definitely improve that.

I moved this to #268 and ....


@monotek you are also right ;)

> ...so the same chart can be installed multiple times in the same namespace.


so I redescribed this issue as only "container-name" and optional
