### ISSUE TITLE
Check if volumePermissions initContainer can be dropped

### ISSUE THREAD

**Issue by mgruner** [zammad/zammad-helm#304]
While fixing https://github.com/zammad/zammad/issues/5412, it seemed that the handling for the `tmp/` path in Zammad could benefit from a similar solution. If we include it in the docker image just like `storage/` with permissions of the Zammad user, the `volumePermissions` `initContainer` may be just obsolete, which would simplify the chart and deployment of Zammad on Kubernetes.

**Comment by mgruner** [comment]
@monotek what do you think about this idea? @klml would this also work on OpenShift?

**Comment by monotek** [comment]
I think it depends on the way /tmp is used.
If it's an emptyDir, it should always work, as it just uses the node filesystem by default, if it's not configured to be a tmpfs.

Imho for that no check is used. 
This should always work or there are deeper non zammad related problems anyway.

**Comment by klml** [comment]
Since openshift wants containers that are as immutable as possible, we can't apply `mkdir -p "${ZAMMAD_DIR}/storage" `

But we have [volumePermissions disabled](https://github.com/zammad/zammad-helm/blob/main/zammad/README.md?plain=1#L104) and thus also the volumePermissions-initContainer. We therefore use an [emptyDir](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir) for the `/tmp` anyway.

So we would be happy with emptydir as default ;)

**Comment by mgruner** [comment]
This does not seem to be feasible. Ruby's `Tempfile.create` refuses directories with global write permission, and that's what we get from `EmptyDir` it seems, no matter if the folder already exists in the container image.

**Comment by mgruner** [comment]
Thanks for the hint. I'm not sure right now if this is something we should generally change.

But this might need to be applied to all pods running the Zammad Rails stack, not the railsserver only.
